INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (1, 'Vitória', 1, 1);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (2, 'Serra', 1, 1);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (3, 'Fundão', 1, 1);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (4, 'Cariacica', 1, 1);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (5, 'Viana', 1, 1);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (6, 'Vila Velha', 1, 1);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (7, 'Guarapari', 1, 1);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (8, 'Itaguaçu', 1, 2);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (9, 'Itarana', 1, 2);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (10, 'Santa Teresa', 1, 2);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (11, 'Santa Maria de Jetibá', 1, 2);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (12, 'Santa Leopoldina', 1, 2);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (13, 'Laranja da Terra', 1, 3);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (14, 'Afonso Cláudio', 1, 3);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (15, 'Brejetuba', 1, 3);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (16, 'Domingos Martins', 1, 3);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (17, 'Marechal Floriano', 1, 3);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (18, 'Venda Nova do Imigrante', 1, 3);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (19, 'Conceição do Castelo', 1, 3);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (20, 'Alfredo Chaves', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (21, 'Anchieta', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (22, 'Piúma', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (23, 'Iconha', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (24, 'Rio Novo do Sul', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (25, 'Itapemirim', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (26, 'Marataízes', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (27, 'Presidente Kennedy', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (28, 'Castelo', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (29, 'Vargem Alta', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (30, 'Cachoeiro de Itapemirim', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (31, 'Jerônimo Monteiro', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (32, 'Muqui', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (33, 'Atílio Vivacqua', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (34, 'Apiacá', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (35, 'Mimoso do Sul', 1, 4);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (36, 'Ibatiba', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (37, 'Irupi', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (38, 'Iúna', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (39, 'Ibitirama', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (40, 'Muniz Freire', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (41, 'Alegre', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (42, 'Divido de São Lourenço', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (43, 'Dores do Rio Preto', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (44, 'Guaçuí', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (45, 'São José do Calçado', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (46, 'Bom Jesus do Norte', 1, 5);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (47, 'Sooretama', 1, 6);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (48, 'Rio Bananal', 1, 6);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (49, 'Linhares', 1, 6);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (50, 'Aracruz', 1, 6);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (51, 'João Neiva', 1, 6);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (52, 'Ibiraçu', 1, 6);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (53, 'São Gabriel da Palha', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (54, 'Vila Valério', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (55, 'São Domingos do Norte', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (56, 'Governador Linde5erg', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (57, 'Pancas', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (58, 'Alto Rio Novo', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (59, 'Baixo Guandu', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (60, 'Colatina', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (61, 'Marilândia', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (62, 'São Roque do Canaã', 1, 7);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (63, 'Mucurici', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (64, 'Ponto Belo', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (65, 'Montanha', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (66, 'Pedro Canário', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (67, 'Pinheiros', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (68, 'Boa Esperança', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (69, 'Conceição da Barra', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (70, 'São Mateus', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (71, 'Jaguaré', 1, 8);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (72, 'Ecoporanga', 1, 9);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (73, 'Água Doce do Norte', 1, 9);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (74, 'Barra de São Francisco', 1, 9);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (75, 'Vila Pavão', 1, 9);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (76, 'Nova Venécia', 1, 9);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (77, 'Mante1polis', 1, 9);
INSERT INTO `siscon`.`adm_municipio` (`id`, `municipio`, `estado_id`, `regiao_id`) VALUES (78, 'Águia Branca', 1, 9);
